este/blog/urls.py
from django.urls import path
from .views import Posts,PostDetalle,crearPost

app_name = 'blog'

urlpatterns = [
    path('', Posts, name='posts'),
    path('<int:post_id>', PostDetalle, name="postdetalle"),
    path('crearPost', crearPost, name="crearPost"),
    path('<str:tema>', Posts)
]

este/proyectodjangoportafolio/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from django.conf.urls.static import static
from django.conf import settings
from menu import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.inicio, name='inicio'),
    path('iniciarSesion/', views.iniciarSesion, name='iniciarSesion'),
    path('crearCuenta/', views.crearCuenta, name='crearCuenta'),
    path('logout/', views.cerrarSesion, name='logout'),
    path('buscar/', views.buscar, name='search'),
    path('portfolio/', include('portafolio.urls')),
    path('blog/', include('blog.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

este/blog/models.py
from django.db import models
from portafolio.models import Usuario
import datetime

# Create your models here.

class Topico(models.Model):
    tema = models.CharField(max_length=200)

    def __str__(self):
        return self.tema

class Post(models.Model):
    titulo = models.CharField(max_length=100) 
    contenido = models.TextField()
    imagen = models.ImageField(upload_to= 'blog/images', null=True)
    fecha = models.DateField(datetime.date.today) 
    user = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    topico = models.ForeignKey(Topico, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.titulo} + {self.user}'

este/blog/forms.py
from django import forms
from portafolio.models import Usuario
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['titulo','contenido', 'topico']

este/blog/views.py
from ast import Not
from lib2to3.pgen2.token import EQEQUAL
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Post, Topico
from .forms import PostForm
from datetime import date

# Create your views here.


def Posts(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''

    temas = Topico.objects.all()
    postMios = Post.objects.filter(user=request.user).order_by('fecha')
    posts = Post.objects.exclude(user=request.user).filter(topico__tema__icontains= q)
    return render(request, 'posts.html', {
        'posts': posts,
        'postMios': postMios,
        'temas': temas,
    })


def PostDetalle(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    return render(request, 'post_detalle.html', {
        'post': post
    })


@login_required
def crearPost(request):
    if request.method == 'GET':
        return render(request, 'crearPost.html', {
            'form': PostForm
        })
    try:
        form = PostForm(request.POST)
        nuevoPost = form.save(commit=False)
        nuevoPost.user = request.user
        nuevoPost.fecha = date.today()
        nuevoPost.save()
        return redirect('/blog')
    except ValueError:
        return render(request, 'crearPost.html', {
            'form': PostForm,
            'error': "ERROR",
        })

este/blog/templates/crearPost.html
{% extends 'layouts/base.html' %}

{% block content %}
    
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button>Publicar</button>
</form>


{% endblock content %}
    

este/blog/templates/post_detalle.html
{% extends 'layouts/base.html' %} {% block content %}
<h1>Post</h1>

<h1>{{post.titulo}}</h1>
<p>{{post.contenido|safe}}</p>
<h3>{{post.fecha}}</h3>

{% endblock %}

este/blog/templates/posts.html
{% extends 'layouts/base.html' %} {% block content %}

<h1><center>Publicaciones</center></h1>

<a href="crearPost">Crear una publicación</a>

<div class="post-container">
  <div>
    <h3>Temas</h3>
    <hr />
    <ul>
      <li>
        <a href="/blog/">Todo</a>
      </li>
      {% for tem in temas %}
      <li>
        <a href="{% url 'blog:posts' %}?q={{tem.tema}}">{{tem.tema}}</a>
      </li>
    {% endfor %}
    </ul>
  </div>
  <div>
    <h2>Mis publicaciones</h2>
    {% for post in postMios %}
    <ul>
      <li>
        <a href="{% url 'blog:postdetalle' post.id %}">{{post.titulo}}</a>
        <p>{{post.contenido|striptags|truncatechars:100}}</p>
        <h3>{{post.fecha|date:'d M Y'|upper}}</h3>
      </li>
    </ul>
    {% endfor %}
    <hr>
    <h2>Publicaciones de la comunidad</h2>
    <ul>
      {% for post in posts %}
      <li>
        <a href="{% url 'blog:postdetalle' post.id %}">{{post.titulo}}</a>
        <p>{{post.contenido|striptags|truncatechars:100}}</p>
        <h3>{{post.fecha|date:'d M Y'|upper}}</h3>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>
 {% endblock %}